title: The Tech Room
author: Okenwa kenneth
email: okenwanonsokenneth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m glad you are here my name is okenwa Kenneth but I guess you already know that. 
  Am a front-end web developer, am guessing you know that already but if you didn't well now you know. 
  I will be talking about programming and Gadgets on this blog.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
